# TAGS & RECEPIES

TAG_NAME_MAX_LENGTH = 64
TAG_SLUG_MAX_LENGTH = 32

INGREDIENT_NAME_MAX_LENGTH = 64
INGREDIENT_MEASUREMENT_UNIT_MAX_LENGTH = 32

RECIPE_NAME_MAX_LENGTH = 128

# USERS

USER_USERNAME_MAX_LENGTH = 64
USER_FIRST_NAME_MAX_LENGTH = 64
USER_LAST_NAME_MAX_LENGTH = 64
USER_EMAIL_MAX_LENGTH = 64
