# TAGS & RECEPIES

COOKING_TIME_MAX_VALUE = 32000
COOKING_TIME_MIN_VALUE = 1

TAG_NAME_MAX_LENGTH = 64
TAG_SLUG_MAX_LENGTH = 32

INGREDIENT_NAME_MAX_LENGTH = 64
INGREDIENT_MEASUREMENT_UNIT_MAX_LENGTH = 32
INGREDIENT_MAX_AMOUNT = 32000
INGREDIENT_MIN_AMOUNT = 1


RECIPE_NAME_MAX_LENGTH = 128


# USERS

USER_USERNAME_MAX_LENGTH = 64
USER_FIRST_NAME_MAX_LENGTH = 64
USER_LAST_NAME_MAX_LENGTH = 64
USER_EMAIL_MAX_LENGTH = 64


# MISC

DEFAULT_TRUNCATE_LEN = 10