name: CI for Foodgram

on:
  push:
    branches: [ master ]

jobs:
  build_and_push_backend_to_docker_hub:
    name: Push Backend Img
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  
      - name: Push to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./backend/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/foodgram_backend:latest


  build_and_push_frontend_to_docker_hub:
    name: Push Frontend Img
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./frontend/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/foodgram_frontend:latest


  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - build_and_push_backend_to_docker_hub
      - build_and_push_frontend_to_docker_hub

    if: github.ref == 'refs/heads/master'
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Copy docker-compose-production.yml via ssh
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        source: "./infra/docker-compose-production.yml"
        target: "/home/${{ secrets.USER }}/foodgram-auto-deploy/"

    - name: Copy nginx.conf via ssh
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        source: "./infra/nginx.conf"
        target: "/home/${{ secrets.USER }}/foodgram-auto-deploy/"

    - name: Execute ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          cd /home/${{ secrets.USER }}/foodgram-auto-deploy/infra/
          sudo docker compose -f docker-compose-production.yml down
          sudo docker compose -f docker-compose-production.yml pull
          sudo docker compose -f docker-compose-production.yml up -d
          sudo docker compose -f docker-compose-production.yml exec backend python manage.py makemigrations
          sudo docker compose -f docker-compose-production.yml exec backend python manage.py migrate
          sudo docker compose -f docker-compose-production.yml exec backend python manage.py collectstatic
          sudo docker compose -f docker-compose-production.yml exec backend cp -r /app/collected_static/. /backend/static/.
